name: Build & Deploy Spring app

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20

      - name: Build Application
        run: |
          mvn clean 
          mvn -B package --file pom.xml
      - name: Build Docker Image
        uses: ac
          


